// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ResortManager1._0.Data;

#nullable disable

namespace Resort_Management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220709062602_AddBookingToDb")]
    partial class AddBookingToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Resort_Management.Models.BookingModel", b =>
                {
                    b.Property<int>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingId"), 1L, 1);

                    b.Property<DateTime>("dateBooked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateForBooking")
                        .HasColumnType("datetime2");

                    b.Property<int>("userbookedId")
                        .HasColumnType("int");

                    b.HasKey("bookingId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Resort_Management.Models.CondosModel", b =>
                {
                    b.Property<int>("condosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("condosId"), 1L, 1);

                    b.Property<int>("condosCapacity")
                        .HasColumnType("int");

                    b.Property<string>("condosLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("condosId");

                    b.ToTable("Condos");
                });

            modelBuilder.Entity("Resort_Management.Models.UserModel", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
